### ISSUE TITLE
gradle buildProduct throws test errors

### ISSUE THREAD

**Issue by johanhenselmans** [credentials/irma_api_server#4]
I tried to compile the irma_api_server. (Mac OS X 10.11.6, Ubuntu 16.0.4.LTS) in both cases the command 'gradle buildProduct' failed at the same place. This is the log from the Ubuntu run (java 8u121-b13-0ubuntu1.16.04.2 , grade 2.10-1)

:preTest
Generating RSA private key, 2048 bit long modulus
..............+++
..............+++
e is 65537 (0x10001)
writing RSA key
writing RSA key
Generating RSA private key, 2048 bit long modulus
......................+++
...........................................................+++
e is 65537 (0x10001)
writing RSA key
writing RSA key
:processTestResources
:testClasses
:test

org.irmacard.api.web.VerificationTest > validSessionTest FAILED
    javax.ws.rs.BadRequestException at VerificationTest.java:137

org.irmacard.api.web.VerificationTest > missingAttributesTest FAILED
    javax.ws.rs.BadRequestException at VerificationTest.java:137

org.irmacard.api.web.VerificationTest > brokenProofTest FAILED
    javax.ws.rs.BadRequestException at VerificationTest.java:137

org.irmacard.api.web.VerificationTest > invalidProofTest FAILED
    javax.ws.rs.BadRequestException at VerificationTest.java:137

org.irmacard.api.web.VerificationTest > authorizedVerifierTest FAILED
    javax.ws.rs.BadRequestException at VerificationTest.java:137

org.irmacard.api.web.VerificationTest > boundProofsTest FAILED
    javax.ws.rs.BadRequestException at VerificationTest.java:137

org.irmacard.api.web.VerificationTest > brokenJsonTest FAILED
    javax.ws.rs.BadRequestException at VerificationTest.java:137

org.irmacard.api.web.VerificationTest > missingMetadataTest FAILED
    javax.ws.rs.BadRequestException at VerificationTest.java:137

org.irmacard.api.web.VerificationTest > unnecessarilySignedJwt FAILED
    javax.ws.rs.BadRequestException at VerificationTest.java:137

org.irmacard.api.web.VerificationTest > missingProofTest FAILED
    javax.ws.rs.BadRequestException at VerificationTest.java:137

org.irmacard.api.web.VerificationTest > unsignedJwt FAILED
    javax.ws.rs.BadRequestException at VerificationTest.java:137

org.irmacard.api.web.IssueTest > validIssueTest FAILED
    javax.ws.rs.BadRequestException at IssueTest.java:167

org.irmacard.api.web.IssueTest > validBoundIssueTest FAILED
    javax.ws.rs.BadRequestException at IssueTest.java:167

org.irmacard.api.web.IssueTest > validBoundIssueTest2 FAILED
    javax.ws.rs.BadRequestException at IssueTest.java:167

org.irmacard.api.web.SignatureTest > validSessionTest FAILED
    javax.ws.rs.BadRequestException at SignatureTest.java:134

org.irmacard.api.web.SignatureTest > validSessionWithInvalidConditionTest FAILED
    javax.ws.rs.BadRequestException at SignatureTest.java:134

org.irmacard.api.web.SignatureTest > oldSignatureSession FAILED
    org.irmacard.credentials.info.KeyException at SignatureTest.java:241

org.irmacard.api.web.SignatureTest > expiredAttributeSession FAILED
    org.irmacard.credentials.info.KeyException at SignatureTest.java:241

org.irmacard.api.web.SignatureTest > verifySigAsDisclosureProofTest FAILED
    javax.ws.rs.BadRequestException at SignatureTest.java:134

org.irmacard.api.web.SignatureTest > validSessionWithConditionTest FAILED
    javax.ws.rs.BadRequestException at SignatureTest.java:134

26 tests completed, 20 failed
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///root/irma_api_server/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 40.28 secs

**Comment by johanhenselmans** [comment]
OK, after some more reading I noticed I should have done 
=============
git submodule init && git submodule update
=============
After that the failed tests dropped down to 2:
=============
org.irmacard.api.web.IssueTest > validBoundIssueTest FAILED
    javax.ws.rs.BadRequestException at IssueTest.java:125

org.irmacard.api.web.IssueTest > validBoundIssueTest2 FAILED
    javax.ws.rs.BadRequestException at IssueTest.java:125

26 tests completed, 2 failed
:test FAILED

FAILURE: Build failed with an exception.
=============

**Comment by sietseringers** [comment]
The public/private keys used in the unit tests were expired. Can you retry with the latest version? (You'll have to run `git submodule update` again.)

**Comment by johanhenselmans** [comment]
Yes, build works now. Thans.
